# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: collections.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'collections.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x63ollections.proto\x12\ralmostrealism\";\n\x13TraversalPolicyData\x12\x0c\n\x04\x64ims\x18\x01 \x03(\x05\x12\x16\n\x0etraversal_axis\x18\x02 \x01(\x05\"m\n\x0e\x43ollectionData\x12<\n\x10traversal_policy\x18\x01 \x01(\x0b\x32\".almostrealism.TraversalPolicyData\x12\x0c\n\x04\x64\x61ta\x18\x02 \x03(\x01\x12\x0f\n\x07\x64\x61ta_32\x18\x03 \x03(\x02\"X\n\x16\x43ollectionLibraryEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x31\n\ncollection\x18\x02 \x01(\x0b\x32\x1d.almostrealism.CollectionData\"S\n\x15\x43ollectionLibraryData\x12:\n\x0b\x63ollections\x18\x01 \x03(\x0b\x32%.almostrealism.CollectionLibraryEntryB\x1c\n\x1aorg.almostrealism.protobufb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'collections_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\032org.almostrealism.protobuf'
  _globals['_TRAVERSALPOLICYDATA']._serialized_start=36
  _globals['_TRAVERSALPOLICYDATA']._serialized_end=95
  _globals['_COLLECTIONDATA']._serialized_start=97
  _globals['_COLLECTIONDATA']._serialized_end=206
  _globals['_COLLECTIONLIBRARYENTRY']._serialized_start=208
  _globals['_COLLECTIONLIBRARYENTRY']._serialized_end=296
  _globals['_COLLECTIONLIBRARYDATA']._serialized_start=298
  _globals['_COLLECTIONLIBRARYDATA']._serialized_end=381
# @@protoc_insertion_point(module_scope)
