/*
 * Copyright 2023 Michael Murray
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

package io.almostrealism.code;

import io.almostrealism.relation.Evaluable;
import io.almostrealism.scope.ArrayVariable;

import java.util.function.BiFunction;
import java.util.function.Supplier;

/**
 * Default implementation of {@link ArgumentProvider} that creates argument variables using a factory function.
 *
 * <p>Argument variables are named using a global counter (of the form {@code _v<n>}); the name is
 * generated by this manager and handed to the variable factory. A custom factory can be supplied to
 * control how the variable is constructed for a given name and input (e.g. to produce a
 * {@code CollectionVariable} instead of a plain {@link ArrayVariable}).</p>
 *
 * @see ArgumentProvider
 * @see ArgumentProvider
 */
public class DefaultScopeInputManager implements ArgumentProvider {
	/** Global counter used to generate unique argument variable names. */
	private static int counter = 0;

	/** Factory that creates an array variable from a generated name and input producer. */
	private BiFunction<String, Supplier<Evaluable<?>>, ArrayVariable<?>> variableFactory;

	/**
	 * Creates a new scope input manager with a custom variable factory.
	 *
	 * <p>The factory receives the generated argument name and the input producer; it is responsible
	 * only for constructing the variable, not for naming it.</p>
	 *
	 * @param variableFactory the factory that creates argument variables from a name and input
	 */
	public DefaultScopeInputManager(BiFunction<String, Supplier<Evaluable<?>>, ArrayVariable<?>> variableFactory) {
		this.variableFactory = variableFactory;
	}

	/**
	 * Returns the next globally-unique argument variable name.
	 *
	 * @return a unique argument name of the form {@code _v<n>}
	 */
	private static String nextArgumentName() {
		return "_v" + counter++;
	}

	/**
	 * {@inheritDoc}
	 *
	 * <p>Creates a new argument variable using the factory, then applies any delegate and offset.
	 *
	 * @param <T> the type of value produced by the input
	 * @param input the input producer
	 * @param delegate the optional delegate variable for memory sharing
	 * @param delegateOffset the offset into the delegate variable
	 * @return the array variable for the input
	 */
	@Override
	public <T> ArrayVariable<T> getArgument(Supplier<Evaluable<? extends T>> input,
											ArrayVariable<T> delegate, int delegateOffset) {
		ArrayVariable arg = variableFactory.apply(nextArgumentName(), (Supplier) input);
		arg.setDelegate(delegate);
		arg.setDelegateOffset(delegateOffset);
		return arg;
	}

}
