# You can specify a custom docker image from Dockerhub as your build environment
image: maven:3.3.3

pipelines:
  default:
    - step:
        script:
          # Maven details
          - mvn --version
          - mvn dependency:copy-dependencies
          - mvn install
          - mvn deploy
