# You can specify a custom docker image from Dockerhub as your build environment
image: maven:3.3.3

pipelines:
  default:
    - step:
        script:
          # Maven details
          - mvn --version

          - rm /usr/share/maven/conf/settings.xml
          - cp ./settings.xml /usr/share/maven/conf/settings.xml

          - mvn dependency:copy-dependencies
          - mvn install
          - mvn deploy
