/*
 * Copyright 2026 Michael Murray
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.flowtree.slack;

import io.flowtree.jobs.ClaudeCodeJob;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.UUID;

/**
 * Configuration for a workstream — a logical unit of work assigned to one or more agents.
 *
 * <p>A workstream groups agents, a git repository, branch lifecycle settings, and optional
 * routing constraints (node labels, dependent repos). It may optionally be connected to a
 * Slack channel ({@code channelId}/{@code channelName}), but this is not required: workstreams
 * can be managed entirely via the ar-manager MCP server or REST API without any Slack
 * integration.</p>
 *
 * <p>The workstream ID can be used as a namespace for MCP memory tool integration,
 * allowing both agents and operators to share context across sessions.</p>
 *
 * @author Michael Murray
 * @see FlowTreeController
 */
public class Workstream {

    /**
     * Connection details for a Flowtree agent.
     *
     * <p>This is retained for optional pre-configured agent lists, but the
     * primary connection model is inbound: agents connect to the controller's
     * {@link io.flowtree.Server} using {@code FLOWTREE_ROOT_HOST} and
     * {@code FLOWTREE_ROOT_PORT}.</p>
     */
    public static class AgentEndpoint {
        /** The hostname or IP address of the agent. */
        private final String host;
        /** The port the agent's FlowTree node is listening on. */
        private final int port;

        /**
         * Creates an agent endpoint with the given host and port.
         *
         * @param host the agent hostname or IP address
         * @param port the agent port number
         */
        public AgentEndpoint(String host, int port) {
            this.host = host;
            this.port = port;
        }

        /** Returns the agent hostname or IP address. */
        public String getHost() {
            return host;
        }

        /** Returns the agent port number. */
        public int getPort() {
            return port;
        }

        /** Returns "host:port" for logging and diagnostics. */
        @Override
        public String toString() {
            return host + ":" + port;
        }
    }

    /** Immutable identifier; used as a memory namespace and for API routing. */
    private final String workstreamId;
    /** The Slack channel ID this workstream receives messages from. */
    private String channelId;
    /** The human-readable Slack channel name for display purposes. */
    private String channelName;
    /** Optional pre-configured agent endpoints (inbound connections are the primary model). */
    private final List<AgentEndpoint> agents;
    /** Branch that agents commit work to by default. */
    private String defaultBranch;
    /** Branch used as the base when the controller creates a new feature branch. */
    private String baseBranch;
    /** Whether agents push completed commits to the remote origin. */
    private boolean pushToOrigin;
    /** Absolute path to the local repository working directory. */
    private String workingDirectory;
    /** Git remote URL; when set the job clones the repo before starting work. */
    private String repoUrl;

    /** Comma-separated list of Claude Code tool names the agent is permitted to use. */
    private String allowedTools;
    /** Maximum agent turns per job; guards against runaway cost. */
    private int maxTurns;
    /** Maximum spending budget per job in USD. */
    private double maxBudgetUsd;

    /**
     * Default Claude Code model alias or full identifier applied to jobs
     * submitted to this workstream when the submission does not specify
     * its own model. {@code null} leaves the {@code --model} flag off so
     * the CLI chooses.
     */
    private String model;

    /**
     * Default Claude Code effort/thinking level applied to jobs submitted
     * to this workstream when the submission does not specify its own
     * effort. {@code null} leaves the {@code --effort} flag off so the
     * CLI chooses.  Must be one of
     * {@link ClaudeCodeJob#VALID_EFFORT_LEVELS} when set.
     */
    private String effort;

    /** Git author name used in commits generated by this workstream's agents. */
    private String gitUserName;
    /** Git author email used in commits generated by this workstream's agents. */
    private String gitUserEmail;

    /** Per-workstream environment variables injected into pushed tool MCP stdio configs. */
    private Map<String, String> env;

    /** Path to a planning document the agent consults for broader goal context. */
    private String planningDocument;

    /** GitHub organization name; selects the org-specific token for GitHub API calls. */
    private String githubOrg;

    /** Additional repository URLs to clone alongside the primary repo. */
    private List<String> dependentRepos;

    /** Default Node labels applied to jobs when no job-level labels are specified. */
    private Map<String, String> requiredLabels;

    /** Slack workspace ID (team ID) that this workstream is bound to; null for single-workspace mode. */
    private String slackWorkspaceId;

    /** Default git user name for new workstreams. */
    public static final String DEFAULT_GIT_USER_NAME = "Flowtree Coding Agent";

    /** Default git user email for new workstreams. */
    public static final String DEFAULT_GIT_USER_EMAIL = "michael@almostrealism.com";

    /**
     * Creates a new workstream with default settings.
     */
    public Workstream() {
        this.workstreamId = UUID.randomUUID().toString();
        this.agents = new ArrayList<>();
        this.pushToOrigin = true;
        this.allowedTools = "Read,Edit,Write,Bash,Glob,Grep";
        this.maxTurns = 800;
        this.maxBudgetUsd = 100.0;
        this.gitUserName = DEFAULT_GIT_USER_NAME;
        this.gitUserEmail = DEFAULT_GIT_USER_EMAIL;
    }

    /**
     * Creates a new workstream with a persistent workstream ID.
     *
     * <p>Use this constructor for workstreams loaded from YAML configuration,
     * where the workstream ID has been previously generated and persisted.</p>
     *
     * @param workstreamId the persistent workstream identifier
     * @param channelId    the Slack channel ID (e.g., "C0123456789")
     * @param channelName  the human-readable channel name (e.g., "#project-agent")
     */
    public Workstream(String workstreamId, String channelId, String channelName) {
        this.workstreamId = workstreamId;
        this.channelId = channelId;
        this.channelName = channelName;
        this.agents = new ArrayList<>();
        this.pushToOrigin = true;
        this.allowedTools = "Read,Edit,Write,Bash,Glob,Grep";
        this.maxTurns = 800;
        this.maxBudgetUsd = 100.0;
    }

    /**
     * Creates a new workstream for the specified channel.
     *
     * @param channelId   the Slack channel ID (e.g., "C0123456789")
     * @param channelName the human-readable channel name (e.g., "#project-agent")
     */
    public Workstream(String channelId, String channelName) {
        this();
        this.channelId = channelId;
        this.channelName = channelName;
    }

    /**
     * Returns the unique workstream identifier.
     * This can be used as a memory namespace for MCP tool integration.
     */
    public String getWorkstreamId() {
        return workstreamId;
    }

    /** Returns the Slack channel ID (e.g., "C0123456789"). */
    public String getChannelId() {
        return channelId;
    }

    /** Sets the Slack channel ID. */
    public void setChannelId(String channelId) {
        this.channelId = channelId;
    }

    /** Returns the human-readable Slack channel name (e.g., "#project-agent"). */
    public String getChannelName() {
        return channelName;
    }

    /** Sets the human-readable Slack channel name. */
    public void setChannelName(String channelName) {
        this.channelName = channelName;
    }

    /** Returns the list of pre-configured agent endpoints for this workstream. */
    public List<AgentEndpoint> getAgents() {
        return agents;
    }

    /**
     * Adds an agent endpoint to this workstream.
     *
     * @param host the agent host
     * @param port the agent port
     * @return this workstream for method chaining
     */
    public Workstream addAgent(String host, int port) {
        agents.add(new AgentEndpoint(host, port));
        return this;
    }

    /** Returns the default git branch that agents commit work to. */
    public String getDefaultBranch() {
        return defaultBranch;
    }

    /**
     * Sets the default git branch for this workstream.
     * Jobs will commit to this branch unless overridden.
     *
     * @param defaultBranch the branch name (e.g., "feature/my-work")
     */
    public void setDefaultBranch(String defaultBranch) {
        this.defaultBranch = defaultBranch;
    }

    /**
     * Returns the base branch used as the starting point when creating
     * a new target branch. Defaults to {@code "master"} if not set.
     */
    public String getBaseBranch() {
        return baseBranch;
    }

    /**
     * Sets the base branch for new branch creation.
     *
     * @param baseBranch the branch name to base new branches on (e.g., "master", "main", "develop")
     */
    public void setBaseBranch(String baseBranch) {
        this.baseBranch = baseBranch;
    }

    /** Returns whether agents push completed commits to the remote origin. */
    public boolean isPushToOrigin() {
        return pushToOrigin;
    }

    /** Sets whether agents should push commits to the remote origin after completing work. */
    public void setPushToOrigin(boolean pushToOrigin) {
        this.pushToOrigin = pushToOrigin;
    }

    /** Returns the local filesystem path to the checked-out repository. */
    public String getWorkingDirectory() {
        return workingDirectory;
    }

    /** Sets the local filesystem path to the checked-out repository. */
    public void setWorkingDirectory(String workingDirectory) {
        this.workingDirectory = workingDirectory;
    }

    /**
     * Returns the git repository URL for automatic checkout.
     *
     * <p>When set (and {@code workingDirectory} is not), the job will
     * clone this repo into a resolved workspace path before starting work.</p>
     */
    public String getRepoUrl() {
        return repoUrl;
    }

    /**
     * Sets the git repository URL for automatic checkout.
     *
     * @param repoUrl the git clone URL (e.g., "https://github.com/owner/repo.git")
     */
    public void setRepoUrl(String repoUrl) {
        this.repoUrl = repoUrl;
    }

    /** Returns the comma-separated list of Claude Code tool names the agent may use. */
    public String getAllowedTools() {
        return allowedTools;
    }

    /** Sets the comma-separated list of allowed Claude Code tool names. */
    public void setAllowedTools(String allowedTools) {
        this.allowedTools = allowedTools;
    }

    /** Returns the maximum number of agent turns allowed per job. */
    public int getMaxTurns() {
        return maxTurns;
    }

    /** Sets the maximum number of agent turns allowed per job. */
    public void setMaxTurns(int maxTurns) {
        this.maxTurns = maxTurns;
    }

    /** Returns the maximum spending budget per job in USD. */
    public double getMaxBudgetUsd() {
        return maxBudgetUsd;
    }

    /** Sets the maximum spending budget per job in USD. */
    public void setMaxBudgetUsd(double maxBudgetUsd) {
        this.maxBudgetUsd = maxBudgetUsd;
    }

    /**
     * Returns the git user name for commits made by this workstream.
     */
    public String getGitUserName() {
        return gitUserName;
    }

    /**
     * Sets the git user name for commits made by this workstream.
     *
     * @param gitUserName the name to use in git commits (e.g., "CI Bot")
     */
    public void setGitUserName(String gitUserName) {
        this.gitUserName = gitUserName;
    }

    /**
     * Returns the git user email for commits made by this workstream.
     */
    public String getGitUserEmail() {
        return gitUserEmail;
    }

    /**
     * Sets the git user email for commits made by this workstream.
     *
     * @param gitUserEmail the email to use in git commits (e.g., "ci-bot@example.com")
     */
    public void setGitUserEmail(String gitUserEmail) {
        this.gitUserEmail = gitUserEmail;
    }

    /**
     * Returns per-workstream environment variables that are injected into
     * pushed tool MCP stdio configs. These override any global env vars
     * defined on the pushed tool entry itself.
     */
    public Map<String, String> getEnv() {
        return env;
    }

    /**
     * Sets per-workstream environment variables for pushed tools.
     *
     * @param env map of environment variable names to values
     */
    public void setEnv(Map<String, String> env) {
        this.env = env;
    }

    /**
     * Returns the optional planning document path for this workstream.
     * When set, agents are instructed to consult this document for the
     * broader goal of the branch.
     */
    public String getPlanningDocument() {
        return planningDocument;
    }

    /**
     * Sets the planning document path for this workstream.
     *
     * @param planningDocument path to the planning document relative to the working directory
     */
    public void setPlanningDocument(String planningDocument) {
        this.planningDocument = planningDocument;
    }

    /**
     * Returns the GitHub organization name for this workstream.
     * When set, the controller proxy uses the org-specific token
     * for GitHub API calls.
     */
    public String getGithubOrg() {
        return githubOrg;
    }

    /**
     * Sets the GitHub organization name for org-based token selection.
     *
     * @param githubOrg the GitHub organization name (e.g., "my-org")
     */
    public void setGithubOrg(String githubOrg) {
        this.githubOrg = githubOrg;
    }

    /**
     * Returns the list of dependent repository URLs that should be
     * checked out alongside the primary repo. Each dependent repo is
     * cloned as a sibling directory and managed with the same branch
     * and commit lifecycle as the primary repo.
     */
    public List<String> getDependentRepos() {
        return dependentRepos;
    }

    /**
     * Sets the dependent repository URLs.
     *
     * @param dependentRepos list of git clone URLs for dependent repos
     */
    public void setDependentRepos(List<String> dependentRepos) {
        this.dependentRepos = dependentRepos;
    }

    /**
     * Returns the Node labels that jobs submitted to this workstream must match by default.
     * When a job submission does not specify {@code requiredLabels}, these labels are applied.
     * Job-level labels always take precedence over workstream-level defaults.
     */
    public Map<String, String> getRequiredLabels() {
        return requiredLabels;
    }

    /**
     * Sets the default Node labels for jobs submitted to this workstream.
     *
     * @param requiredLabels map of label key-value pairs (e.g., {"platform": "macos"})
     */
    public void setRequiredLabels(Map<String, String> requiredLabels) {
        this.requiredLabels = requiredLabels;
    }

    /**
     * Returns the Slack workspace ID (team ID, e.g. "T0123456789") that this workstream
     * is bound to.  When {@code null}, the workstream belongs to the first (or only)
     * workspace connection, maintaining backward compatibility with single-workspace mode.
     */
    public String getSlackWorkspaceId() {
        return slackWorkspaceId;
    }

    /**
     * Sets the Slack workspace ID for this workstream.
     *
     * @param slackWorkspaceId the Slack team ID (T...) or {@code null} for default workspace
     */
    public void setSlackWorkspaceId(String slackWorkspaceId) {
        this.slackWorkspaceId = slackWorkspaceId;
    }

    /**
     * Returns the default Claude Code model for this workstream, or
     * {@code null} when no default is set.
     */
    public String getModel() {
        return model;
    }

    /**
     * Sets the default Claude Code model for this workstream.  Empty or
     * {@code null} clears the default so the CLI chooses.  Validated
     * immediately against {@link ClaudeCodeJob#VALID_MODELS} so workstream
     * registration with an unrecognised model fails fast — preventing the
     * dispatched Claude subprocess from returning a 404 and looping the
     * enforce-changes machinery indefinitely.
     *
     * @param model a value from {@link ClaudeCodeJob#VALID_MODELS}, or
     *              {@code null}/empty to clear
     * @throws IllegalArgumentException if {@code model} is non-empty and
     *                                  not a recognised identifier
     */
    public void setModel(String model) {
        if (model == null || model.isEmpty()) {
            this.model = null;
            return;
        }
        if (!ClaudeCodeJob.VALID_MODELS.contains(model)) {
            throw new IllegalArgumentException("Invalid model '" + model
                    + "'. Must be one of " + ClaudeCodeJob.VALID_MODELS);
        }
        this.model = model;
    }

    /**
     * Returns the default Claude Code effort/thinking level for this
     * workstream, or {@code null} when no default is set.
     */
    public String getEffort() {
        return effort;
    }

    /**
     * Sets the default Claude Code effort/thinking level for this
     * workstream.  Validated immediately against
     * {@link ClaudeCodeJob#VALID_EFFORT_LEVELS} so misconfiguration fails
     * at the caller rather than silently at job dispatch.
     *
     * @param effort one of {@link ClaudeCodeJob#VALID_EFFORT_LEVELS}, or
     *               {@code null}/empty to clear
     * @throws IllegalArgumentException if {@code effort} is non-empty and
     *                                  not a recognised level
     */
    public void setEffort(String effort) {
        if (effort == null || effort.isEmpty()) {
            this.effort = null;
            return;
        }
        if (!ClaudeCodeJob.VALID_EFFORT_LEVELS.contains(effort)) {
            throw new IllegalArgumentException(
                    "Invalid effort level '" + effort + "'. Must be one of "
                    + ClaudeCodeJob.VALID_EFFORT_LEVELS);
        }
        this.effort = effort;
    }

    /**
     * Returns the next agent endpoint using round-robin selection.
     * This method is thread-safe.
     *
     * @return the next agent, or null if no agents are configured
     */
    public AgentEndpoint getNextAgent() {
        if (agents.isEmpty()) {
            return null;
        }
        // Simple round-robin - could be enhanced with availability checking
        synchronized (agents) {
            AgentEndpoint agent = agents.remove(0);
            agents.add(agent);
            return agent;
        }
    }

    /**
     * Returns a JSON object representing this workstream's configuration and capabilities,
     * suitable for inclusion in the {@code GET /api/workstreams} list response.
     *
     * <p>All string fields are JSON-escaped. Optional fields are omitted when null or empty.
     * Computed fields: {@code hasPlanningDocument}, {@code pipelineCapable}.</p>
     *
     * @return a JSON object string (not an array)
     */
    public String toSummaryJson() {
        StringBuilder json = new StringBuilder();
        json.append("{");
        json.append("\"workstreamId\":\"").append(escapeForJson(workstreamId)).append("\"");

        if (channelName != null) {
            json.append(",\"channelName\":\"").append(escapeForJson(channelName)).append("\"");
        }
        if (defaultBranch != null) {
            json.append(",\"defaultBranch\":\"").append(escapeForJson(defaultBranch)).append("\"");
        }
        if (baseBranch != null) {
            json.append(",\"baseBranch\":\"").append(escapeForJson(baseBranch)).append("\"");
        }
        if (repoUrl != null) {
            json.append(",\"repoUrl\":\"").append(escapeForJson(repoUrl)).append("\"");
        }
        if (githubOrg != null) {
            json.append(",\"githubOrg\":\"").append(escapeForJson(githubOrg)).append("\"");
        }
        if (slackWorkspaceId != null) {
            json.append(",\"slackWorkspaceId\":\"").append(escapeForJson(slackWorkspaceId)).append("\"");
        }
        if (planningDocument != null && !planningDocument.isEmpty()) {
            json.append(",\"planningDocument\":\"").append(escapeForJson(planningDocument)).append("\"");
        }
        if (model != null && !model.isEmpty()) {
            json.append(",\"model\":\"").append(escapeForJson(model)).append("\"");
        }
        if (effort != null && !effort.isEmpty()) {
            json.append(",\"effort\":\"").append(escapeForJson(effort)).append("\"");
        }

        boolean pipelineCapable = repoUrl != null && !repoUrl.isEmpty();
        json.append(",\"hasPlanningDocument\":").append(planningDocument != null && !planningDocument.isEmpty());
        json.append(",\"pipelineCapable\":").append(pipelineCapable);

        if (dependentRepos != null && !dependentRepos.isEmpty()) {
            json.append(",\"dependentRepos\":[");
            boolean first = true;
            for (String repo : dependentRepos) {
                if (!first) json.append(",");
                first = false;
                json.append("\"").append(escapeForJson(repo)).append("\"");
            }
            json.append("]");
        }

        if (requiredLabels != null && !requiredLabels.isEmpty()) {
            json.append(",\"requiredLabels\":{");
            boolean first = true;
            for (Map.Entry<String, String> entry : requiredLabels.entrySet()) {
                if (!first) json.append(",");
                first = false;
                json.append("\"").append(escapeForJson(entry.getKey())).append("\":");
                json.append("\"").append(escapeForJson(entry.getValue())).append("\"");
            }
            json.append("}");
        }

        json.append("}");
        return json.toString();
    }

    /**
     * Escapes a string for safe inclusion as a JSON string value.
     *
     * @param s the string to escape, or {@code null}
     * @return the escaped string, never {@code null}
     */
    private static String escapeForJson(String s) {
        if (s == null) return "";
        return s.replace("\\", "\\\\")
                .replace("\"", "\\\"")
                .replace("\n", "\\n")
                .replace("\r", "\\r");
    }

    @Override
    public String toString() {
        return "Workstream{" +
               "workstreamId='" + workstreamId + '\'' +
               ", channelName='" + channelName + '\'' +
               ", agents=" + agents.size() +
               ", defaultBranch='" + defaultBranch + '\'' +
               '}';
    }
}
