/*
 * Copyright 2023 Michael Murray
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.almostrealism.music.pattern;

import org.almostrealism.audio.CellFeatures;
import org.almostrealism.music.data.ParameterSet;
import org.almostrealism.music.notes.NoteAudioChoice;
import org.almostrealism.io.Console;
import org.almostrealism.io.ConsoleFeatures;

import java.util.List;
import java.util.Objects;
import java.util.stream.Collectors;
import java.util.stream.IntStream;
import java.util.stream.Stream;

/**
 * Generates seed {@link PatternLayer}s for a pattern using a specific note audio choice.
 *
 * <p>{@code PatternLayerSeeds} encapsulates the configuration for populating the root
 * level of a pattern hierarchy. It generates layers at regular intervals determined by
 * the granularity relative to the total pattern duration.</p>
 *
 * @see PatternLayerManager
 */
public class PatternLayerSeeds implements ConsoleFeatures {

	/** The measure position where seed generation begins. */
	private double position;
	/** The granularity fraction relative to duration used to compute layer scale. */
	private double granularity;
	/** The minimum allowed layer scale in measures. */
	private final double minScale;
	/** The maximum allowed layer scale in measures. */
	private final double maxScale;
	/** The bias value influencing element activation probability. */
	private double bias;

	/** The note audio choice used for elements generated by this seed. */
	private final NoteAudioChoice choice;
	/** The parameter set used when generating elements. */
	private final ParameterSet params;

	/** Creates a {@code PatternLayerSeeds} with default values and no choice or params. */
	public PatternLayerSeeds() {
		this(0, 1.0, 0.0625, 64.0, 0.0, null, null);
	}

	/**
	 * Creates a {@code PatternLayerSeeds} with the given configuration.
	 *
	 * @param position    starting measure position for seed generation
	 * @param granularity fraction of duration used to compute layer scale
	 * @param minScale    minimum allowed layer scale in measures
	 * @param maxScale    maximum allowed layer scale in measures
	 * @param bias        element activation bias
	 * @param choice      the note audio choice for generated elements
	 * @param params      the parameter set for element generation
	 */
	public PatternLayerSeeds(double position, double granularity, double minScale, double maxScale,
							 double bias, NoteAudioChoice choice, ParameterSet params) {
		this.position = position;
		this.granularity = granularity;
		this.minScale = minScale;
		this.maxScale = maxScale;
		this.bias = bias;
		this.choice = choice;
		this.params = params;
	}

	/** Returns the starting measure position for seed generation. */
	public double getPosition() {
		return position;
	}
	/** Sets the starting measure position for seed generation. */
	public void setPosition(double position) {
		this.position = position;
	}

	/**
	 * Returns the layer scale for the given duration, clamped to {@code [minScale, maxScale]}.
	 *
	 * @param duration the pattern duration in measures
	 * @return the layer scale in measures
	 */
	public double getScale(double duration) {
		return Math.min(maxScale, Math.max(minScale, duration * granularity));
	}

	/**
	 * Returns the layer scale for the given duration, clamped to at least {@code min}.
	 *
	 * @param duration the pattern duration in measures
	 * @param min      the effective minimum scale
	 * @return the layer scale in measures
	 */
	public double getScale(double duration, double min) {
		return Math.max(min, getScale(duration));
	}

	/** Returns the granularity fraction used to compute the layer scale. */
	public double getGranularity() {
		return granularity;
	}
	/** Sets the granularity fraction used to compute the layer scale. */
	public void setGranularity(double granularity) {
		this.granularity = granularity;
	}

	/** Returns the element activation bias. */
	public double getBias() { return bias; }
	/** Sets the element activation bias. */
	public void setBias(double bias) { this.bias = bias; }

	/**
	 * Generates a stream of seed {@link PatternLayer}s for the given duration.
	 *
	 * @param factory                the element factory
	 * @param offset                 the measure offset
	 * @param duration               the pattern duration in measures
	 * @param scaleTraversalStrategy the scale traversal strategy for generated elements
	 * @param scaleTraversalDepth    the scale traversal depth
	 * @param minScale               the minimum layer scale
	 * @return a stream of generated pattern layers
	 */
	public Stream<PatternLayer> generator(PatternElementFactory factory, double offset, double duration,
										  ScaleTraversalStrategy scaleTraversalStrategy,
										  int scaleTraversalDepth, double minScale) {
		double g = getScale(duration, minScale);
		double count = Math.max(1.0, duration / g) + 1;

		List<PatternLayer> layers = IntStream.range(0, (int) count)
				.mapToObj(i ->
						factory.apply(null, position + offset + i * g, g,
								this.bias, scaleTraversalStrategy, scaleTraversalDepth,
								false, choice.isMelodic(), params).orElse(null))
				.filter(Objects::nonNull)
				.map(List::of)
				.map(elements -> new PatternLayer(choice, elements))
				.collect(Collectors.toList());

		if (layers.size() <= 0 && (this.bias) >= 1.0) {
			warn("No seeds generated, despite bias >= 1.0");
		}

		return layers.stream();
	}

	@Override
	public Console console() { return CellFeatures.console; }
}
