#!/usr/bin/env python3
"""
Extract SkyTNT midi-model (tv2o-medium) weights from HuggingFace safetensors format
to AR protobuf format loadable by StateDictionary.

This script:
1. Loads model.safetensors from a HuggingFace model directory using the safetensors library
2. Converts bfloat16 weights to float32
3. Exports each tensor to CollectionLibraryData protobuf format (the StateDictionary format)
4. Groups output into component files for efficient loading

Usage:
    python extract_skytnt_weights.py skytnt/midi-model-tv2o-medium ./weights_output

The model_dir argument can be:
  - A local directory containing model.safetensors (e.g. a downloaded HuggingFace repo)
  - A HuggingFace model ID (e.g. skytnt/midi-model-tv2o-medium) — the script will look for
    model.safetensors in the HuggingFace cache, or you can pre-download with:
      python -c "from huggingface_hub import snapshot_download; snapshot_download('skytnt/midi-model-tv2o-medium')"

Output structure (flat directory, loaded by StateDictionary.java):
    output_dir/
      net_embeddings         -- net.embed_tokens.weight + net.norm.weight
      net_layer_00           -- net.layers.0.* (9 or 10 weights)
      ...
      net_layer_11           -- net.layers.11.*
      net_token_embeddings   -- net_token.embed_tokens.weight + net_token.norm.weight
      net_token_layer_00     -- net_token.layers.0.*
      net_token_layer_01     -- net_token.layers.1.*
      net_token_layer_02     -- net_token.layers.2.*
      lm_head                -- lm_head.weight

Weight key names are preserved exactly as in HuggingFace (e.g. "net.layers.0.self_attn.q_proj.weight").
StateDictionary.get("net.layers.0.self_attn.q_proj.weight") will work directly.

Requires:
    pip install safetensors torch
    ./engine/ml/scripts/generate_protobuf_python.sh  (to generate collections_pb2.py)

Expected weight shapes (from planning doc §4.2):
    net.embed_tokens.weight                              [3406, 1024]
    net.layers.{i}.self_attn.{q,k,v,o}_proj.weight      [1024, 1024]  i=0..11
    net.layers.{i}.mlp.gate_proj.weight                  [4096, 1024]
    net.layers.{i}.mlp.up_proj.weight                    [4096, 1024]
    net.layers.{i}.mlp.down_proj.weight                  [1024, 4096]
    net.layers.{i}.{input,post_attention}_layernorm.weight [1024]
    net.norm.weight                                      [1024]
    net_token.embed_tokens.weight                        [3406, 1024]
    net_token.layers.{i}.self_attn.{q,k,v,o}_proj.weight [1024, 1024]  i=0..2
    net_token.layers.{i}.mlp.{gate,up,down}_proj.weight  [1024, 1024]
    net_token.layers.{i}.{input,post_attention}_layernorm.weight [1024]
    net_token.norm.weight                                [1024]
    lm_head.weight                                       [3406, 1024]
"""

import argparse
import numpy as np
import os
import sys
from pathlib import Path

try:
    from safetensors import safe_open
except ImportError:
    print("Error: safetensors not found. Install with: pip install safetensors")
    sys.exit(1)

try:
    import torch
except ImportError:
    print("Error: torch is required for bfloat16 conversion. Install with: pip install torch")
    sys.exit(1)

# Import the protobuf definitions (generated by generate_protobuf_python.sh
# from this repo's .proto source files in engine/ml/src/main/proto/).
# The scripts directory is three levels up from src/main/python/.
try:
    _scripts_dir = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                                '..', '..', '..', 'scripts')
    sys.path.insert(0, os.path.abspath(_scripts_dir))
    import collections_pb2 as collections
except ImportError:
    print("Error: collections_pb2.py not found in engine/ml/scripts/.")
    print("Generate it by running:")
    print("  ./engine/ml/scripts/generate_protobuf_python.sh")
    print()
    print("This requires: pip install grpcio-tools")
    sys.exit(1)

# Maximum serialized size per output file (stay under protobuf's 2 GB limit).
PROTOBUF_SIZE_LIMIT = 1024 * 1024 * 1024

# Expected tensor count for tv2o-medium per planning doc §4.2.
# The actual file may contain additional computed tensors (e.g. rotary_emb.inv_freq).
# A warning is printed if the count differs from this range.
EXPECTED_COUNT_MIN = 140
EXPECTED_COUNT_MAX = 160

# Expected shapes for key tensors (used for verification output only).
EXPECTED_SHAPES = {
    "net.embed_tokens.weight": [3406, 1024],
    "net.norm.weight": [1024],
    "net_token.embed_tokens.weight": [3406, 1024],
    "net_token.norm.weight": [1024],
    "lm_head.weight": [3406, 1024],
}

for _i in range(12):
    _p = f"net.layers.{_i}"
    EXPECTED_SHAPES[f"{_p}.self_attn.q_proj.weight"] = [1024, 1024]
    EXPECTED_SHAPES[f"{_p}.self_attn.k_proj.weight"] = [1024, 1024]
    EXPECTED_SHAPES[f"{_p}.self_attn.v_proj.weight"] = [1024, 1024]
    EXPECTED_SHAPES[f"{_p}.self_attn.o_proj.weight"] = [1024, 1024]
    EXPECTED_SHAPES[f"{_p}.mlp.gate_proj.weight"] = [4096, 1024]
    EXPECTED_SHAPES[f"{_p}.mlp.up_proj.weight"] = [4096, 1024]
    EXPECTED_SHAPES[f"{_p}.mlp.down_proj.weight"] = [1024, 4096]
    EXPECTED_SHAPES[f"{_p}.input_layernorm.weight"] = [1024]
    EXPECTED_SHAPES[f"{_p}.post_attention_layernorm.weight"] = [1024]

for _i in range(3):
    _p = f"net_token.layers.{_i}"
    EXPECTED_SHAPES[f"{_p}.self_attn.q_proj.weight"] = [1024, 1024]
    EXPECTED_SHAPES[f"{_p}.self_attn.k_proj.weight"] = [1024, 1024]
    EXPECTED_SHAPES[f"{_p}.self_attn.v_proj.weight"] = [1024, 1024]
    EXPECTED_SHAPES[f"{_p}.self_attn.o_proj.weight"] = [1024, 1024]
    EXPECTED_SHAPES[f"{_p}.mlp.gate_proj.weight"] = [1024, 1024]
    EXPECTED_SHAPES[f"{_p}.mlp.up_proj.weight"] = [1024, 1024]
    EXPECTED_SHAPES[f"{_p}.mlp.down_proj.weight"] = [1024, 1024]
    EXPECTED_SHAPES[f"{_p}.input_layernorm.weight"] = [1024]
    EXPECTED_SHAPES[f"{_p}.post_attention_layernorm.weight"] = [1024]


def numpy_to_collection_data(array):
    """Convert a float32 numpy array to a CollectionData protobuf."""
    collection_data = collections.CollectionData()
    traversal_policy = collections.TraversalPolicyData()
    for dim in array.shape:
        traversal_policy.dims.append(int(dim))
    traversal_policy.traversal_axis = 0
    collection_data.traversal_policy.CopyFrom(traversal_policy)
    flattened = array.flatten().astype(np.float32)
    collection_data.data_32.extend(flattened.tolist())
    return collection_data


def make_entry(key, array):
    """Create a CollectionLibraryEntry from a key and float32 numpy array."""
    entry = collections.CollectionLibraryEntry()
    entry.key = key
    entry.collection.CopyFrom(numpy_to_collection_data(array))
    return entry


def estimate_size(entry):
    """Estimate serialized byte size of a CollectionLibraryEntry."""
    key_size = len(entry.key.encode('utf-8'))
    data_size = len(entry.collection.data_32) * 4
    dims_size = len(entry.collection.traversal_policy.dims) * 4
    return key_size + data_size + dims_size + 100


def write_protobuf_file(entries, file_path):
    """Write a list of CollectionLibraryEntry items to a binary protobuf file."""
    library_data = collections.CollectionLibraryData()
    library_data.collections.extend(entries)
    with open(file_path, 'wb') as f:
        f.write(library_data.SerializeToString())
    total_params = sum(len(e.collection.data_32) for e in entries)
    print(f"  Wrote {len(entries)} tensors ({total_params:,} params) to {file_path}")


def write_group(entries, output_dir, prefix):
    """Write a group of entries to one or more files, splitting if over the size limit."""
    if not entries:
        return

    current = []
    current_size = 0
    file_index = 0

    for entry in entries:
        entry_size = estimate_size(entry)
        if current_size + entry_size > PROTOBUF_SIZE_LIMIT and current:
            write_protobuf_file(current, os.path.join(output_dir, f"{prefix}_{file_index}"))
            current = []
            current_size = 0
            file_index += 1
        current.append(entry)
        current_size += entry_size

    if current:
        suffix = f"_{file_index}" if file_index > 0 else ""
        write_protobuf_file(current, os.path.join(output_dir, f"{prefix}{suffix}"))


def load_safetensors(safetensors_path):
    """
    Load all tensors from a safetensors file.

    Returns a dict mapping key -> float32 numpy array.
    Bfloat16 tensors are converted to float32 via PyTorch.
    """
    state = {}
    with safe_open(str(safetensors_path), framework="pt", device="cpu") as f:
        keys = list(f.keys())
        print(f"Found {len(keys)} tensors in {safetensors_path}")
        for key in keys:
            tensor = f.get_tensor(key)
            array = tensor.float().cpu().numpy()
            state[key] = array
    return state


def verify_shapes(state):
    """Print shape verification for all expected keys. Return True if all match."""
    print("\nShape verification:")
    all_ok = True
    missing_keys = []
    shape_mismatches = []

    for key, expected_shape in sorted(EXPECTED_SHAPES.items()):
        if key not in state:
            missing_keys.append(key)
            all_ok = False
        else:
            actual_shape = list(state[key].shape)
            match = actual_shape == expected_shape
            status = "OK" if match else "MISMATCH"
            print(f"  [{status}] {key}: {actual_shape}"
                  + (f" (expected {expected_shape})" if not match else ""))
            if not match:
                shape_mismatches.append((key, expected_shape, actual_shape))
                all_ok = False

    if missing_keys:
        print(f"\nMissing {len(missing_keys)} expected keys:")
        for key in missing_keys:
            print(f"  MISSING: {key}")

    if shape_mismatches:
        print(f"\nShape mismatches ({len(shape_mismatches)}):")
        for key, expected, actual in shape_mismatches:
            print(f"  {key}: expected {expected}, got {actual}")

    return all_ok


def group_key(key):
    """
    Return the output file prefix for a given weight key.

    Groups:
      - net_embeddings:          net.embed_tokens.weight, net.norm.weight
      - net_layer_NN:            net.layers.{N}.*
      - net_token_embeddings:    net_token.embed_tokens.weight, net_token.norm.weight
      - net_token_layer_NN:      net_token.layers.{N}.*
      - lm_head:                 lm_head.weight
      - other:                   any unrecognized key (printed as warning)
    """
    if key.startswith("net.layers."):
        layer_num = int(key.split("net.layers.")[1].split(".")[0])
        return f"net_layer_{layer_num:02d}"
    if key.startswith("net_token.layers."):
        layer_num = int(key.split("net_token.layers.")[1].split(".")[0])
        return f"net_token_layer_{layer_num:02d}"
    if key.startswith("net."):
        return "net_embeddings"
    if key.startswith("net_token."):
        return "net_token_embeddings"
    if key.startswith("lm_head."):
        return "lm_head"
    return "other"


def extract_weights(state, output_dir):
    """Write all weights grouped into component protobuf files."""
    os.makedirs(output_dir, exist_ok=True)

    groups = {}
    unrecognized = []

    for key in sorted(state.keys()):
        prefix = group_key(key)
        if prefix == "other":
            unrecognized.append(key)
        entry = make_entry(key, state[key])
        groups.setdefault(prefix, []).append(entry)

    if unrecognized:
        print(f"\nWARNING: {len(unrecognized)} unrecognized key(s) written to 'other':")
        for key in unrecognized:
            print(f"  {key}: {list(state[key].shape)}")

    print(f"\nWriting {len(groups)} protobuf group(s) to {output_dir}:")

    # Write in a deterministic order
    for prefix in sorted(groups.keys()):
        write_group(groups[prefix], output_dir, prefix)

    print(f"\nExtraction complete. {len(state)} tensors written to {output_dir}")


def main():
    parser = argparse.ArgumentParser(
        description="Extract SkyTNT midi-model weights from safetensors to AR protobuf format")
    parser.add_argument("model_dir", type=str,
                        help="Directory containing model.safetensors "
                             "(or HuggingFace model ID)")
    parser.add_argument("output_dir", type=str,
                        help="Output directory for protobuf files")

    args = parser.parse_args()

    # Locate model.safetensors
    model_dir = Path(args.model_dir)
    safetensors_path = model_dir / "model.safetensors"

    if not safetensors_path.exists():
        # Try treating as a HuggingFace cache path
        print(f"model.safetensors not found at {safetensors_path}")
        print("Hint: download the model first with:")
        print(f"  python -c \"from huggingface_hub import snapshot_download; "
              f"snapshot_download('{args.model_dir}')\"")
        sys.exit(1)

    print(f"Loading weights from: {safetensors_path}")
    state = load_safetensors(safetensors_path)

    total = len(state)
    print(f"\nTotal tensors loaded: {total}")

    if total < EXPECTED_COUNT_MIN or total > EXPECTED_COUNT_MAX:
        print(f"WARNING: Expected {EXPECTED_COUNT_MIN}–{EXPECTED_COUNT_MAX} tensors "
              f"for tv2o-medium, but found {total}.")
    else:
        print(f"Tensor count {total} is within expected range "
              f"[{EXPECTED_COUNT_MIN}, {EXPECTED_COUNT_MAX}].")

    print("\nFull tensor inventory:")
    for key in sorted(state.keys()):
        print(f"  {key}: {list(state[key].shape)}")

    shapes_ok = verify_shapes(state)
    if not shapes_ok:
        print("\nWARNING: Some shapes do not match expectations (see above).")
    else:
        print("\nAll expected shapes match.")

    extract_weights(state, args.output_dir)
    print("\nDone!")


if __name__ == "__main__":
    main()
