#!/usr/bin/env python3
"""
Generalized safetensors -> AR StateDictionary extractor core.

This module is the reusable engine behind the ``extract_<model>_weights.py``
scripts (see ``engine/ml/CLAUDE.md``). It is intentionally *model agnostic*:
a concrete extractor (e.g. ``extract_sa3_weights.py``) supplies a key-remapping
spec and this module does the rest.

Three responsibilities:

1. ``load_safetensors(path)`` reads a ``.safetensors`` checkpoint into a
   ``dict[str, numpy.ndarray]``, upcasting ``bfloat16`` to ``float32`` (the
   StateDictionary protobuf only carries ``double``/``float``).
2. ``remap(state, rules)`` applies an ordered list of rules. Each rule is a
   plain ``dict -> dict`` callable; the helpers in this module
   (``select_prefix``, ``strip_prefix``, ``rename``, ``fold_weight_norm``,
   ``check_shapes``, ...) build the common shapes of ``(match, rename,
   transform)`` rule described in the Phase 1 component plan.
3. ``write_state_dictionary(state, out_dir)`` serializes to the *same*
   protobuf shard format the DiT / AE loaders already consume, reusing the
   ``numpy_to_collection_data`` / ``write_protobuf_file`` core unchanged. The
   torch-based ``extract_stable_audio_autoencoder.py`` imports these writer
   functions from here so there is a single implementation.

This module has **no torch dependency** so the core and its unit tests run
without PyTorch or any model weights. ``safetensors`` is imported lazily inside
``load_safetensors`` so the writer/remap helpers (and their tests) work even
where ``safetensors`` is not installed.
"""

import os
import re
import struct
import sys

import numpy as np

# The protobuf bindings (collections_pb2, generated by
# generate_protobuf_python.sh from this repo's .proto source files in
# engine/ml/src/main/proto/) are imported lazily. Only the StateDictionary
# writer/reader path (numpy_to_collection_data, write_protobuf_file,
# read_state_dictionary) needs them; the remap/fold helpers and the
# reference-activation dumps (save_reference_output / dump_reference_activations)
# are pure struct/numpy. Deferring the import lets a consumer that only dumps
# reference activations (e.g. dump_same_references.py) run on a fresh checkout
# without first generating collections_pb2 (which requires grpcio-tools).
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
collections = None


def _require_collections():
    """Import the generated ``collections_pb2`` protobuf bindings on demand.

    Raises a descriptive :class:`ImportError` if the generated module is
    absent, pointing at the generator script. Cached after the first call.
    """
    global collections
    if collections is None:
        try:
            import collections_pb2 as generated
        except ImportError as exc:  # pragma: no cover - environment guard
            raise ImportError(
                "collections_pb2.py not found in the scripts directory. "
                "Generate it with ./engine/ml/scripts/generate_protobuf_python.sh "
                "(requires: pip install grpcio-tools). Note: only the "
                "StateDictionary writer/reader needs it; reference-activation "
                "dumps do not.") from exc
        collections = generated
    return collections

# A single protobuf message must stay comfortably under the 2GB hard limit;
# this matches the sharding threshold used by the other extractors.
PROTOBUF_SIZE_LIMIT = 1024 * 1024 * 1024


# ---------------------------------------------------------------------------
# safetensors loading
# ---------------------------------------------------------------------------

def load_safetensors(path):
    """Read a ``.safetensors`` checkpoint into ``dict[str, numpy.ndarray]``.

    Tensors stored as ``bfloat16`` (and other non-fp32 floating types) are
    upcast to ``float32`` because the StateDictionary protobuf carries only
    ``double`` / ``float`` payloads. Integer tensors are preserved as-is.

    The read goes through ``safetensors.safe_open`` so only the requested
    tensors are materialized. ``safetensors`` is imported here (not at module
    scope) so the rest of this module is usable without it installed.
    """
    try:
        from safetensors import safe_open
    except ImportError as exc:  # pragma: no cover - environment guard
        raise ImportError(
            "safetensors is required to read .safetensors checkpoints. "
            "Install with: pip install safetensors") from exc

    # Importing ml_dtypes registers a numpy-compatible ``bfloat16`` dtype, which
    # safetensors' numpy backend needs to return bf16 tensors (numpy has no
    # native bf16). Best-effort: if it is absent, fp32/fp16 still load and a bf16
    # checkpoint surfaces a clear error rather than a cryptic one.
    try:  # pragma: no cover - exercised indirectly by bf16 test
        import ml_dtypes  # noqa: F401
    except ImportError:
        pass

    state = {}
    with safe_open(path, framework="numpy") as handle:
        for key in handle.keys():
            state[key] = _upcast(handle.get_tensor(key))
    return state


def _upcast(array):
    """Upcast any floating tensor to float32; leave integer tensors alone.

    ``safetensors`` returns numpy arrays directly for fp32/fp16/integer
    tensors. ``bfloat16`` has no numpy dtype, so older/newer ``safetensors``
    builds may surface it either as a ``ml_dtypes`` bfloat16 array or refuse to
    return it as numpy at all; in both cases ``astype(np.float32)`` performed by
    the caller path below normalizes it. We detect "not a standard numpy float"
    by checking the dtype kind.
    """
    if not isinstance(array, np.ndarray):
        # Some backends hand back a framework tensor; coerce via numpy.
        array = np.asarray(array)
    if array.dtype.kind == "f" and array.dtype != np.float32:
        return array.astype(np.float32)
    if array.dtype.kind == "V":
        # Structured/opaque dtype (e.g. a bfloat16 view) -> force float32.
        return array.astype(np.float32)
    return array


# ---------------------------------------------------------------------------
# Remapping
# ---------------------------------------------------------------------------

def remap(state, rules):
    """Apply an ordered list of ``dict -> dict`` rules to ``state``.

    Rules are applied left to right; the output of each rule feeds the next.
    A rule is any callable taking the current ``dict[str, ndarray]`` and
    returning a new one. The builder helpers below cover the common cases:
    selection (keep a subset), renaming (prefix strip / rename), per-tensor
    transforms (dtype, transpose), and group transforms (weight-norm folding).
    """
    for rule in rules:
        state = rule(state)
    return state


def _matcher(match):
    """Coerce ``match`` into a ``key -> bool`` predicate.

    ``match`` may be ``None`` (match everything), a string (prefix match), a
    compiled regular expression (search), or a callable predicate.
    """
    if match is None:
        return lambda key: True
    if callable(match) and not hasattr(match, "search"):
        return match
    if hasattr(match, "search"):
        return lambda key: match.search(key) is not None
    if isinstance(match, str):
        return lambda key: key.startswith(match)
    raise TypeError("Unsupported match specification: %r" % (match,))


def _renamer(rename):
    """Coerce ``rename`` into a ``key -> key`` function.

    ``rename`` may be ``None`` (identity), a ``(old, new)`` prefix-replacement
    tuple, or a callable.
    """
    if rename is None:
        return lambda key: key
    if isinstance(rename, tuple) and len(rename) == 2:
        old, new = rename
        return lambda key: (new + key[len(old):]) if key.startswith(old) else key
    if callable(rename):
        return rename
    raise TypeError("Unsupported rename specification: %r" % (rename,))


def rule(match=None, rename=None, transform=None):
    """Build a per-key rule from a ``(match, rename, transform)`` triple.

    Keys matching ``match`` are renamed via ``rename`` and have their array
    passed through ``transform`` (an ``ndarray -> ndarray`` callable). Keys
    that do not match pass through unchanged. A rename that collides with an
    existing output key raises ``ValueError`` so silent weight loss is caught.
    """
    matches = _matcher(match)
    do_rename = _renamer(rename)

    def apply(state):
        out = {}
        for key, array in state.items():
            if matches(key):
                new_key = do_rename(key)
                if transform is not None:
                    array = transform(array)
            else:
                new_key = key
            if new_key in out:
                raise ValueError("Remap rule produced duplicate key: %s" % new_key)
            out[new_key] = array
        return out

    return apply


def select(match):
    """Keep only the keys matching ``match``; drop the rest."""
    matches = _matcher(match)
    return lambda state: {k: v for k, v in state.items() if matches(k)}


def select_prefix(prefix):
    """Keep only the keys starting with ``prefix``; drop the rest."""
    return select(prefix)


def drop(match):
    """Drop the keys matching ``match``; keep the rest."""
    matches = _matcher(match)
    return lambda state: {k: v for k, v in state.items() if not matches(k)}


def strip_prefix(prefix):
    """Rename keys starting with ``prefix`` by removing that prefix."""
    return rule(match=prefix, rename=(prefix, ""))


def rename_prefix(old, new):
    """Rename keys starting with ``old`` so the prefix becomes ``new``."""
    return rule(match=old, rename=(old, new))


def rename_regex(pattern, repl):
    """Rename keys by ``re.sub(pattern, repl, key)`` for matching keys."""
    compiled = re.compile(pattern)
    return rule(match=compiled, rename=lambda key: compiled.sub(repl, key))


def fold_weight_norm(g_suffix=".weight_g", v_suffix=".weight_v",
                     out_suffix=".weight", eps=1e-12):
    """Fold PyTorch weight-norm ``(weight_g, weight_v)`` pairs into one weight.

    For every key ending in ``g_suffix`` whose sibling ``v_suffix`` exists, emit
    ``out_suffix`` holding ``g * v / (||v|| + eps)`` where the norm is taken over
    every dimension except output channel 0 (matching ``torch.nn.utils.weight_norm``
    with ``dim=0`` for conv weights). The ``g``/``v`` keys are removed; all other
    keys pass through. This is the reusable form of the folding previously inlined
    in ``extract_stable_audio_autoencoder.py``.
    """
    def apply(state):
        out = {}
        consumed = set()
        for key in state:
            if key.endswith(g_suffix):
                base = key[: -len(g_suffix)]
                v_key = base + v_suffix
                if v_key in state:
                    weight_g = state[key].astype(np.float32)
                    weight_v = state[v_key].astype(np.float32)
                    axes = tuple(range(1, weight_v.ndim))
                    norm = np.sqrt(np.sum(weight_v * weight_v, axis=axes, keepdims=True))
                    folded = weight_g * weight_v / (norm + eps)
                    out[base + out_suffix] = folded.astype(np.float32)
                    consumed.add(key)
                    consumed.add(v_key)
        for key, array in state.items():
            if key in consumed:
                continue
            if key in out:
                raise ValueError("Weight-norm folding collided on key: %s" % key)
            out[key] = array
        return out

    return apply


def check_shapes(expected):
    """Identity rule that asserts each key in ``expected`` has the given shape.

    ``expected`` maps key -> shape tuple. A missing key or a shape mismatch
    raises ``ValueError``. Keys absent from ``expected`` are not checked. Use
    this to fail fast when a checkpoint's layout drifts from what a consumer
    expects.
    """
    def apply(state):
        for key, shape in expected.items():
            if key not in state:
                raise ValueError("Expected key missing from state: %s" % key)
            actual = tuple(state[key].shape)
            if actual != tuple(shape):
                raise ValueError(
                    "Shape mismatch for %s: expected %s, got %s"
                    % (key, tuple(shape), actual))
        return state

    return apply


# ---------------------------------------------------------------------------
# Protobuf writer (shared, reused unchanged by the other extractors)
# ---------------------------------------------------------------------------

def numpy_to_collection_data(array):
    """Convert a numpy array to a ``CollectionData`` protobuf (float32 payload)."""
    pb = _require_collections()
    collection_data = pb.CollectionData()

    traversal_policy = pb.TraversalPolicyData()
    for dim in array.shape:
        traversal_policy.dims.append(int(dim))
    traversal_policy.traversal_axis = 0
    collection_data.traversal_policy.CopyFrom(traversal_policy)

    flattened = np.asarray(array).flatten().astype(np.float32)
    collection_data.data_32.extend(flattened.tolist())

    return collection_data


def make_entry(key, array):
    """Create a ``CollectionLibraryEntry`` from a key and a numpy array."""
    entry = _require_collections().CollectionLibraryEntry()
    entry.key = key
    entry.collection.CopyFrom(numpy_to_collection_data(array))
    return entry


def estimate_size(entry):
    """Estimate the serialized size of a ``CollectionLibraryEntry`` in bytes."""
    key_size = len(entry.key.encode("utf-8"))
    data_size = len(entry.collection.data_32) * 4
    dims_size = len(entry.collection.traversal_policy.dims) * 4
    return key_size + data_size + dims_size + 100


def write_protobuf_file(entries, file_path):
    """Serialize and write ``CollectionLibraryData`` to a binary file."""
    library_data = _require_collections().CollectionLibraryData()
    library_data.collections.extend(entries)

    with open(file_path, "wb") as f:
        f.write(library_data.SerializeToString())

    total_params = sum(len(e.collection.data_32) for e in entries)
    print(f"  Wrote {len(entries)} weight tensors ({total_params:,} params) to {file_path}")


def write_group(entries, output_dir, prefix):
    """Write a group of entries, splitting into shards under the size limit.

    Returns the list of file paths actually written (in write order), so callers
    can report exactly what was produced rather than re-scanning the directory.
    """
    if not entries:
        return []

    written = []
    current = []
    current_size = 0
    file_index = 0

    for entry in entries:
        entry_size = estimate_size(entry)
        if current_size + entry_size > PROTOBUF_SIZE_LIMIT and current:
            path = os.path.join(output_dir, f"{prefix}_{file_index}")
            write_protobuf_file(current, path)
            written.append(path)
            current = []
            current_size = 0
            file_index += 1
        current.append(entry)
        current_size += entry_size

    if current:
        suffix = f"_{file_index}" if file_index > 0 else ""
        path = os.path.join(output_dir, f"{prefix}{suffix}")
        write_protobuf_file(current, path)
        written.append(path)

    return written


def write_state_dictionary(state, out_dir, shard_prefix="weights"):
    """Write a remapped ``dict[str, ndarray]`` to StateDictionary protobuf shards.

    Files are written into ``out_dir`` (created if needed) as ``shard_prefix`` /
    ``shard_prefix_1`` / ... when the size limit forces multiple shards. The
    StateDictionary loader reads every non-hidden file in the directory, so the
    shard names are arbitrary. Keys are written in sorted order for a stable,
    diff-friendly layout.

    Any stale shard left from a prior run with the same ``shard_prefix`` is
    removed before writing: because the loader reads every non-hidden file in the
    directory, a leftover same-prefix shard would silently pollute a later load.
    Returns exactly the list of file paths written by this call (sorted), tracked
    from :func:`write_group` rather than re-scanned from disk.
    """
    os.makedirs(out_dir, exist_ok=True)

    # Clear stale same-prefix shards from a previous run so they cannot pollute a
    # later StateDictionary load (the loader reads every non-hidden file).
    for name in os.listdir(out_dir):
        if name == shard_prefix or name.startswith(shard_prefix + "_"):
            stale = os.path.join(out_dir, name)
            if os.path.isfile(stale):
                os.remove(stale)

    entries = [make_entry(key, state[key]) for key in sorted(state.keys())]
    written = write_group(entries, out_dir, shard_prefix)
    return sorted(written)


def read_state_dictionary(path):
    """Read StateDictionary protobuf shard(s) back into ``dict[str, ndarray]``.

    ``path`` may be a single shard file or a directory of shards. This mirrors
    the Java ``StateDictionary`` directory read and exists so Python tests can
    round-trip ``write_state_dictionary`` output without a JVM. Arrays are
    reshaped to their stored ``traversal_policy.dims``.
    """
    if os.path.isdir(path):
        files = sorted(
            os.path.join(path, name)
            for name in os.listdir(path)
            if not name.startswith(".") and os.path.isfile(os.path.join(path, name))
        )
    else:
        files = [path]

    state = {}
    for file_path in files:
        library_data = _require_collections().CollectionLibraryData()
        with open(file_path, "rb") as f:
            library_data.ParseFromString(f.read())
        for entry in library_data.collections:
            dims = tuple(entry.collection.traversal_policy.dims)
            if entry.collection.data_32:
                values = np.array(entry.collection.data_32, dtype=np.float32)
            else:
                values = np.array(entry.collection.data, dtype=np.float32)
            state[entry.key] = values.reshape(dims) if dims else values
    return state


# ---------------------------------------------------------------------------
# Reference activation dumps (for the C2 per-stage parity tests)
# ---------------------------------------------------------------------------

def save_reference_output(array, filepath):
    """Save a tensor as the simple ``[uint32 count][float32 ...]`` reference format.

    Accepts a numpy array or anything ``np.asarray`` can flatten to float32
    (including a detached torch tensor via ``.cpu().float().numpy()`` supplied by
    the caller). This is the format the Java parity tests read.
    """
    arr = np.asarray(array).astype(np.float32).flatten()
    with open(filepath, "wb") as f:
        f.write(struct.pack("<I", len(arr)))
        f.write(arr.tobytes())


def read_reference_output(filepath):
    """Read a ``save_reference_output`` file back into a flat float32 array."""
    with open(filepath, "rb") as f:
        count = struct.unpack("<I", f.read(4))[0]
        data = f.read(count * 4)
    return np.frombuffer(data, dtype="<f4").astype(np.float32)


def dump_reference_activations(stages, out_dir):
    """Write a name -> activation mapping as per-stage reference ``.bin`` files.

    ``stages`` maps a stage name (e.g. ``"test_input"``, ``"resampling_stage_0"``,
    ``"encoder_output"``, ``"decoder_output"``) to a numpy array. Each is written
    to ``out_dir/<name>.bin`` via :func:`save_reference_output`. Returns the list
    of written paths. Block C2's parity tests load these files one stage at a
    time. The activations themselves must come from a real reference forward pass
    (see :func:`run_reference_stages`); this function only serializes them.
    """
    os.makedirs(out_dir, exist_ok=True)
    written = []
    for name, array in stages.items():
        path = os.path.join(out_dir, f"{name}.bin")
        save_reference_output(array, path)
        written.append(path)
    return written


def run_reference_stages(model, test_input, stage_names=None):
    """Run a staged reference model and collect its per-stage activations.

    ``model`` is any callable ``ndarray -> dict[str, ndarray]`` that maps the
    seeded input to a mapping of stage name -> activation (this is the hook the
    real PyTorch SAME forward implements in the C2 effort; the unit tests supply
    a synthetic stub). The returned mapping always includes ``"test_input"``.
    If ``stage_names`` is given, the result is restricted (and ordered) to those
    names plus ``"test_input"``, raising ``KeyError`` if a requested stage is
    absent — so a wiring change that drops a stage fails loudly.
    """
    stages = {"test_input": np.asarray(test_input).astype(np.float32)}
    produced = model(test_input)
    if not isinstance(produced, dict):
        raise TypeError("Reference model must return dict[str, ndarray] of stages")
    if stage_names is None:
        for name, array in produced.items():
            stages[name] = np.asarray(array).astype(np.float32)
    else:
        for name in stage_names:
            if name == "test_input":
                continue
            if name not in produced:
                raise KeyError("Reference model did not produce stage: %s" % name)
            stages[name] = np.asarray(produced[name]).astype(np.float32)
    return stages


# ---------------------------------------------------------------------------
# Generic CLI driver (used by thin per-model entry points)
# ---------------------------------------------------------------------------

def extract(safetensors_path, out_dir, rules, shard_prefix="weights"):
    """Load -> remap -> write, the full path a thin config entry point invokes.

    Returns the remapped state so a caller can additionally generate reference
    dumps. Prints a short inventory for operator visibility.
    """
    print(f"Loading safetensors: {safetensors_path}")
    state = load_safetensors(safetensors_path)
    print(f"  {len(state)} source tensors")

    mapped = remap(state, rules)
    print(f"Remapped to {len(mapped)} tensors")
    for key in sorted(mapped.keys()):
        print(f"  {key}: {list(mapped[key].shape)}")

    paths = write_state_dictionary(mapped, out_dir, shard_prefix=shard_prefix)
    print(f"Wrote {len(paths)} shard(s) to {out_dir}")
    return mapped
