/*
 * Copyright 2025 Michael Murray
 * All Rights Reserved
 */

/**
 * Hierarchical timeseries types for the spatial audio visualization system.
 *
 * <p>This package provides tree-structured timeseries implementations that combine
 * audio data references with spatial frequency visualization. It is built on top
 * of {@link org.almostrealism.spatial.FrequencyTimeseriesAdapter} and the
 * {@link io.almostrealism.relation.Tree} interface.</p>
 *
 * <h2>Core Classes</h2>
 * <ul>
 *   <li>{@link org.almostrealism.spatial.series.SimpleTimeseries} — base class for
 *       tree-structured timeseries with an optional {@link org.almostrealism.spatial.series.SoundDataTimeseries}
 *       delegate</li>
 *   <li>{@link org.almostrealism.spatial.series.RecordedTimeseries} — represents
 *       captured audio recordings, optionally grouped in a tree hierarchy</li>
 *   <li>{@link org.almostrealism.spatial.series.AudioModelOutput} — represents
 *       audio generated by ML models, carrying model name, conditioning text, and
 *       embedding vectors</li>
 *   <li>{@link org.almostrealism.spatial.series.SoundDataTimeseries} — bridges
 *       {@link org.almostrealism.spatial.SoundData} with
 *       {@link org.almostrealism.spatial.SpatialWaveDetails} for playback and
 *       visualization</li>
 * </ul>
 */
package org.almostrealism.spatial.series;
