/*
 * Copyright 2025 Michael Murray
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

package io.almostrealism.scope;

import io.almostrealism.code.ComputableBase;
import io.almostrealism.lang.CodePrintWriter;
import io.almostrealism.relation.Parent;

import java.util.ArrayList;
import java.util.Collection;
import java.util.List;
import java.util.function.Consumer;
import java.util.function.Function;
import java.util.stream.Collectors;

/**
 * A {@link Scope} that combines an explicit code segment with an optional
 * {@link CodeGenerator} for the scope body.
 *
 * <p>A {@code HybridScope} is the preferred replacement for the deprecated
 * {@link ExplicitScope}. It delegates argument management to an embedded
 * {@link ExplicitScope} while allowing child scopes generated by the
 * framework to be appended in the normal way. At write time, if a
 * {@link CodeGenerator} has been set it is invoked; otherwise the
 * explicit scope's code buffer is used.</p>
 *
 * @param <T> the return type of the scope
 */
public class HybridScope<T> extends Scope<T> {
	/** The explicit code segment that holds the manually written body and kernel arguments. */
	private final ExplicitScope<T> explicit;

	/** An optional code generator that produces the scope body from the scope and language. */
	private CodeGenerator codeGenerator;

	/**
	 * Creates a {@link HybridScope} from a {@link ComputableBase}, extracting its function name,
	 * metadata, arguments, and compute requirements.
	 *
	 * @param operation the computable operation that supplies the scope configuration
	 */
	public HybridScope(ComputableBase operation) {
		super(operation.getFunctionName(), operation.getMetadata());
		this.explicit = new ExplicitScope<T>(operation);

		if (operation.getComputeRequirements() != null) {
			setComputeRequirements(operation.getComputeRequirements());
		}
	}

	/**
	 * Creates a {@link HybridScope} from an existing {@link ExplicitScope} and a
	 * {@link CodeGenerator}.
	 *
	 * @param explicit       the explicit scope providing the code buffer and arguments
	 * @param generator      the code generator for the scope body; may be {@code null}
	 */
	public HybridScope(ExplicitScope<T> explicit, CodeGenerator generator) {
		this.explicit = explicit;
		this.codeGenerator = generator;
	}

	/**
	 * Sets the explicit list of kernel arguments by delegating to the embedded
	 * {@link ExplicitScope}.
	 *
	 * @param arguments the argument list to use
	 */
	public void setArguments(List<Argument<?>> arguments) { explicit.setArguments(arguments); }

	/**
	 * Derives the kernel arguments from a collection of variable dependencies and stores
	 * them in the embedded {@link ExplicitScope}.
	 *
	 * @param dependencies the variables whose arguments should be extracted
	 */
	public void setDependencies(Collection<Variable<?, ?>> dependencies) {
		explicit.setArguments(Scope.extractArgumentDependencies(dependencies));
	}

	/**
	 * Returns the embedded {@link ExplicitScope} that holds the manual code buffer and arguments.
	 *
	 * @return the explicit scope component
	 */
	public ExplicitScope<T> getExplicit() {
		return explicit;
	}

	/**
	 * Replaces the {@link CodeGenerator} used to produce the scope body at write time.
	 *
	 * @param source the new code generator; may be {@code null} to fall back to the explicit buffer
	 */
	public void setSource(CodeGenerator source) {
		this.codeGenerator = source;
	}

	/**
	 * {@inheritDoc}
	 *
	 * <p>Writes the parent scope header, then either invokes the {@link CodeGenerator}
	 * (if set) or delegates to the embedded {@link ExplicitScope}.</p>
	 */
	@Override
	public void write(CodePrintWriter w) {
		super.write(w);

		if (codeGenerator == null) {
			explicit.write(w);
		} else {
			w.println(codeGenerator.generate(this, w.getLanguage()));
		}
	}

	/**
	 * Returns a {@link Consumer} that appends strings to the embedded explicit scope's
	 * code buffer.
	 *
	 * @return a consumer that accumulates code strings
	 */
	public Consumer<String> code() { return explicit.code(); }

	/**
	 * {@inheritDoc}
	 *
	 * <p>Delegates to the embedded {@link ExplicitScope#isInlineable()}.</p>
	 */
	@Override
	public boolean isInlineable() { return explicit.isInlineable(); }

	/**
	 * {@inheritDoc}
	 *
	 * <p>Creates a new {@link HybridScope} sharing the same explicit segment and code
	 * generator, then populates it with the provided child scopes.</p>
	 */
	@Override
	public Parent<Scope<T>> generate(List<Scope<T>> children) {
		Scope<T> scope = new HybridScope<>(explicit, codeGenerator);
		scope.setName(getName());
		scope.setMetadata(getMetadata());
		scope.getChildren().addAll(children);
		return scope;
	}

	/**
	 * {@inheritDoc}
	 *
	 * <p>Merges arguments from both the explicit scope and the parent scope,
	 * removing duplicates before applying the mapper.</p>
	 */
	@Override
	protected <A> List<A> arguments(Function<Argument<?>, A> mapper) {
		List<Argument<?>> args = new ArrayList<>();
		args.addAll(explicit.arguments(Function.identity()));
		args.addAll(super.arguments(Function.identity()));
		return Scope.removeDuplicateArguments(args).stream().map(mapper).collect(Collectors.toList());
	}
}
