name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main

env:
  JAVA_VERSION: '17'

permissions:
  contents: write
  pull-requests: write

jobs:
  common:
    name: common
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: adopt
          cache: 'maven'
      - name: Prepare
        run: |
          mkdir /usr/java ; mkdir /usr/java/packages
      - name: Build
        run: |
         mvn package \
           -DAR_HARDWARE_DRIVER=native \
           -DAR_HARDWARE_LIBS=/usr/java/packages/lib \
           -Djava.library.path=/usr/java/packages/lib
